version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "anime-news"
s3_bucket = "codeanding"
s3_prefix = "anime-news"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
profile = "codeanding"
